#!/usr/bin/env bash

echo "Please enter EFI paritition: (example /dev/sda1 or /dev/nvme0n1p1)"
read EFI

echo "Please enter SWAP paritition: (example /dev/sda2)"
read SWAP

echo "Please enter Root(/) paritition: (example /dev/sda3)"
read ROOT

echo "Please enter your username"
read USER 

echo "Please enter your password"
read PASSWORD 

# Formatting
mkfs.fat -F32 "${EFI}"
mkswap "${SWAP}"
swapon "${SWAP}"
mkfs.ext4 "${ROOT}"

# Mount target
mount "${ROOT}" /mnt
mkdir /mnt/boot
mount "${EFI}" /mnt/boot/

# Linux kernel and Grub
pacstrap -K /mnt base linux linux-firmware --noconfirm --needed
pacstrap -K /mnt grub efibootmgr --noconfirm --needed

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# cat command into eof.sh so to run it in chroot
cat <<REALEND > /mnt/eof.sh

# Grub
pacman -S grub efibootmgr --noconfirm --needed
grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot
grub-mkconfig -o /boot/grub/grub.cfg

# Edit pacman.conf
sed -i 's/Colour/#Colour/' /etc/pacman.conf
sed -i 's/#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
sed -i 's/#[multilib]\#Include/[multilib]\Include/' /etc/pacman.conf

# Display
pacman -S vulkan-radeon libva-mesa-driver mesa-vdpau --noconfirm --needed

# Desktop environment
pacman -S git vim openssh fakeroot base-devel sddm networkmanager packagekit-qt5 --noconfirm --needed
pacman -S xorg xorg-server pipewire wireplumber pulseaudio pipewire-pulse intel-ucode nvtop --noconfirm --needed
pacman -S plasma-meta konsole kwrite dolphin ark plasma-workspace egl-wayland --noconfirm --needed
pacman -S sudo firefox noto-fonts-cjk noto-fonts-emoji --noconfirm --needed
pacman -S sudo vivaldi power-profiles-daemon --noconfirm --needed

# Display, firmware
sudo pacman -Syy && -Syu
sudo pacman -S mesa-vdpau linux-firmware packagekit-qt5 fwupd flatpak linux linux-headers --noconfirm --needed
sudo pacman -S flameshot steam fuse2 unrar libreoffice-still-zh-tw  qt5-wayland qt6-wayland partitionmanager power-profiles-daemon --noconfirm --needed
sudo pacman -S fcitx5-im fcitx5-qt fcitx5-gtk fcitx5-table-extra avahi --noconfirm --needed

# Users
echo $PASSWORD | passwd
useradd -m $USER
usermod -aG wheel,storage,power,audio,video $USER
echo $USER:$PASSWORD | chpasswd
sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

sed -i 's/^#zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=zh_TW.UTF-8" >> /etc/locale.conf

ln -sf /usr/share/zoneinfo/Asia/HongKong /etc/localtime
hwclock --systohc
sudo timedatectl set-local-rtc 1 --adjust-system-clock

echo "ArchLinux" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 ArchLinux" >> /etc/hosts

systemctl enable sddm.service
systemctl enable sshd.service
systemctl enable bluetooth.service
systemctl enable NetworkManager.service

REALEND

# chroot
arch-chroot /mnt sh eof.sh
