#!/usr/bin/env bash

echo "Please enter your username"
read USER 

echo "Please enter your password"
read PASSWORD 

# Formatting
mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3

# Mount target
mount /dev/nvme0n1p3 /mnt
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot/

# Linux kernel
pacstrap -K /mnt base linux linux-firmware --noconfirm --needed

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Grub command into grub.sh so to run it in chroot
cat <<REALEND > /mnt/boot/grub.sh
pacstrap -K /mnt grub efibootmgr --noconfirm --needed
mount /dev/nvme0n1p1 /boot
grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot
grub-mkconfig -o /boot/grub/grub.cfg
exit
REALEND

# cat command into eof.sh so to run it in chroot
cat <<REALEND > /mnt/eof.sh
# Display
pacman -S vulkan-radeon libva-mesa-driver mesa-vdpau --noconfirm --needed

# Desktop environment
pacman -S sudo networkmanager vim firefox noto-fonts-cjk noto-fonts-emoji --noconfirm --needed
pacman -S plasma-meta konsole kwrite dolphin ark plasma-workspace egl-wayland --noconfirm --needed
pacman -S xorg xorg-server pipewire wireplumber pulseaudio pipewire-pulse intel-ucode nvtop --noconfirm --needed
pacman -S sddm packagekit-qt5 --noconfirm --needed
pacman -S git openssh fakeroot base-devel bluez bluez-utils blueman --noconfirm --needed

# Users
useradd -m $USER
usermod -aG wheel,storage,power,audio,video $USER
echo $USER:$PASSWORD | chpasswd
sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

ln -sf /usr/share/zoneinfo/Asia/HongKong /etc/localtime
hwclock --systohc

echo "ArchLinux" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 ArchLinux" >> /etc/hosts

systemctl enable sddm.service
systemctl enable sshd.service
systemctl enable bluetooth.service
systemctl enable NetworkManager.service

exit 
unmount /mnt/boot
unmount /mnt
reboot now

REALEND

# chroot
arch-chroot /mnt sh eof.sh
