#!/usr/bin/env bash

echo "Please enter your username"
read USER 

echo "Please enter your password"
read PASSWORD 

# Formatting
mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3

# Mount target
mount /dev/nvme0n1p3 /mnt
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot/

# Linux kernel
pacstrap -K /mnt base linux linux-firmware --noconfirm --needed

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# chroot
arch-chroot /mnt
