#!/bin/bash

# Check user privilege
if [ $(whoami) != "root" ]; then
  echo "Please run this script with root privileges!"
  exit 1
fi

# Check for disk argument
if [ $# -ne 2 ]; then
  echo "Please specify the disk to format and desired swap size!"
  echo "Usage: $0 /dev/sdX <swap_size_in_GiB>"
  exit 1
fi

disk=$1
swap_size=$2

# Check if disk exists
if [ ! -block "$disk" ]; then
  echo "Disk $disk does not exist!"
  exit 1
fi

# Check disk size
size=$(fdisk -s $disk)

# Create GPT partition table
parted $disk << EOF
mklabel gpt
EOF

# Create EFI partition
parted $disk << EOF
set 1 flags boot
mkpart primary 1 1 512MiB
set 1 type fat32
label 1 efi
EOF

# Calculate remaining space for data partition after swap
data_start=$(($size - $(($swap_size * 1024)) * 1024 * 1024))

# Create swap partition with specified size
parted $disk << EOF
set 2 flags swap
mkpart primary 2 512MiB $data_start
label 2 swap
EOF

# Create Linux data partition with remaining space
parted $disk << EOF
mkpart primary 3 $data_start $(($size - 1))
label 3 linux-data
EOF

# Format EFI partition
mkfs.fat -F32 $disk1

# Format swap partition
mkswap $disk2

# Format Linux data partition
mkfs.ext4 $disk3

echo "Disk $disk formatted successfully!"
